Added domain name for IRI in the API
HTTP-APIs/hydrus pull request #527
Opened 2020-11-11 15:59 UTC by farazkhanfk7

Fixes #507 

### Checklist
- [x] My branch is up-to-date with upstream/develop branch.
- [x] Everything works and tested for Python 3.6.0 and above.

### Description

All paths starting with ```/...``` are changed with ```http://localhost:8000/...``` so that the link can be followed by clicking/reading/dereferencing the string. I have created a get_host_domain function to get the localhost and port. Please let me know if this isn't the right approach.

### Change logs

-  Added get_host_domain function in _conf.py_

- Changed f-strings to get new links.

New Output at ```http://localhost:8080/serverapi/DatastreamCollection```:
```
{
   "@context": "http://localhost:8080/serverapi/contexts/DatastreamCollection.jsonld",
   "@id": "http://localhost:8080/serverapi/DatastreamCollection/",
   "@type": "DatastreamCollection",
   "hydra:totalItems": 0,
   "hydra:view": {
   "@id": "http://localhost:8080/serverapi/DatastreamCollection?page=1",
   "@type": "hydra:PartialCollectionView",
   "hydra:first": "http://localhost:8080/serverapi/DatastreamCollection?page=1",
   "hydra:last": "http://localhost:8080/serverapi/DatastreamCollection?page=1"
   },
```

2020-11-13 06:07 UTC, priyanshunayan requested changes
The approach looks good and we might also want full IRIs in the entrypoint too. Currently `/serverapi` returns the following output:
```json{
    "@context": "/serverapi/contexts/EntryPoint.jsonld",
    "@id": "/serverapi",
    "@type": "EntryPoint",
    "Area": "/serverapi/Area",
    "Command": "/serverapi/Command",
    "Datastream": "/serverapi/Datastream",
    "Drone": "/serverapi/Drone",
    "LogEntry": "/serverapi/LogEntry",
    "Message": "/serverapi/Message",
    ....
```

2020-11-13 06:39 UTC, farazkhanfk7 commented
Okay @priyanshunayan . I guess I missed this point in the issue that we have to do the same for `/serverapi` as well but now I'll make these changes. Thanks for reviewing.

2020-11-13 09:50 UTC, raoashish10 commented
@farazkhanfk7 That is what I have thought too, changes in hydra_python_core would be easier and would reflect everywhere in the returned api doc I think. Maybe try changing the DocUrl?

2020-11-13 10:11 UTC, farazkhanfk7 commented
@raoashish10  Yes. I was thinking the same like the changes you made in this [PR](https://github.com/HTTP-APIs/hydra-python-core/pull/61)

2020-11-22 16:23 UTC, priyanshunayan reviewed
Was keeping `"hydra:template"` as relative IRI intentional? Also since we have all the `@id`s absolute can we also change `@id` of supportedOperation?

2020-11-23 06:23 UTC, farazkhanfk7 commented
> Was keeping "hydra:template" as relative IRI intentional?

`"hydra:template"` currently returns something like this `/serverapi/DroneCollection{?DroneState[Speed], DroneState[Position], DroneState[Direction],.......}",` so I wasn't sure about this one. But now I will make these changes. 

 > Also since we have all the @ids absolute can we also change @id of supportedOperation ?

I went through the link attached. Currently ids in supportedOperation look like `"@id": "_:dronecollection_retrieve",` . I skipped this because I wasn't sure about adding host domain here and what it should look like . What do you think should be the expected behaviour here ?

2020-11-23 06:51 UTC, farazkhanfk7 commented
@priyanshunayan The checks are failing because currently the HydraIriTemplate class in master branch of hydra_python_core doesn't have a base_url in it's __init__ function  otherwise it works on local machine. What should I do in this case ? Should I revert back these changes or wait ?

2020-11-24 04:09 UTC, priyanshunayan commented
I am not sure if we really need ids of `supportedOperations` expanded as they are not being referred from anywhere, every id is unique.  But again, having expanded IRIs everywhere will make the output consistent. 

@Mec-iS Do you want to weigh in?

2020-11-24 10:57 UTC, Mec-iS commented
you mean the link to the hydra core vocabulary? this should be defined in the context and referenced using `hydra:...`

2020-11-24 11:15 UTC, priyanshunayan commented
@Mec-iS  Suppose we take this excerpt of the present output:
```json
 "supportedOperation": [
                {
                    "@id": "_:dronecollection_retrieve",
                    "@type": "http://schema.org/FindAction",
                   ....
                },
```
So, should the `@id` be in expanded form, given that it's a blank node, so do you suggest using [Skolem IRIs](https://www.w3.org/2011/rdf-wg/wiki/Skolemisation) to use in place of blank nodes or it's better off in the present form?

2020-11-24 11:22 UTC, Mec-iS commented
no. we don't need to name blank nodes as we are not going to expose them to external networks.

2020-11-24 11:29 UTC, farazkhanfk7 commented
Do we need any other changes or is this fine ?

2020-11-24 11:32 UTC, priyanshunayan approved these changes
LGTM 🚀  Thank you for the contribution.

2020-11-24 11:43 UTC, Mec-iS commented
This should fix #507 

@chrizandr @xadahiya please double-check and merge

2020-11-27 05:52 UTC, farazkhanfk7 commented
@priyanshunayan  @Mec-iS  I have also made a small change in test_Index in test_app.py due to which these checks are failing because the complementary PR in hydra_python_core needs to be merged first. Also the `endpoints['@id']` now gives `http://hydrus.com/demoapi`. Please double-check.

2020-12-26 06:28 UTC, farazkhanfk7 commented
@chrizandr Can you please review this and the complementary PR in hydra_python_core ? Actually I accidentally deleted my fork of hydrus and can't continue with this branch now :(   If this still need some changes should I create a new PR ?

2021-01-10 13:11 UTC, Mec-iS commented
this PR is not passing CI/CD. Please see error stacktrace in TravisCI

2021-01-10 15:05 UTC, farazkhanfk7 commented
@Mec-iS These checks are failing because changes for full IRIs were also made in **hydra_python_core**'s develop branch in this [PR](https://github.com/HTTP-APIs/hydra-python-core/pull/62) , but Travis CI is still using the master branch of hydra_python_core to run these tests. 
A test failed because I also updated test_app.py's test_Index because `endpoints['@id']` will return `'http://hydrus.com/demoapi'` instead of `'/demoapi'`. I ran all the tests on my machine with pytest and they passed. 
What should I do in this case ? Should I wait for merging of master <- develop in hydra_python_core ?

2021-01-10 15:07 UTC, Mec-iS commented
ok. so first we have to merge on the core @chrizandr @xadahiya please go on with merging

2021-01-10 15:27 UTC, chrizandr commented
Core is now synced up, starting a rebuild before we can merge

2021-01-10 15:27 UTC, closed without merging